version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
  pre_build:
    commands:
      - echo "Install dependencies..."
      - yarn install --frozen-lockfile
      - echo "Dependencies completed sucess..."
  build:
    commands:
      - yarn build
      - echo "Build completed sucess..."
